<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user-PC" name="Test1" tests="2" failures="2" timestamp="10 Nov 2019 20:55:11 GMT" time="0.091" errors="0">
  <testcase name="test1" time="0.03" classname="com.actitime.genericlib.Testngparalleldemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.actitime.genericlib.Testngparalleldemo.test1(Testngparalleldemo.java:11)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.035" classname="com.actitime.genericlib.Testngparalleldemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.actitime.genericlib.Testngparalleldemo.test2(Testngparalleldemo.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test1 -->
